

INSERT INTO BANK_TRANSACTION_CODE( CODE,NAME,ENTRY_TYPE ) VALUES( 10,'CREDIT',	10);
INSERT INTO BANK_TRANSACTION_CODE( CODE,NAME,ENTRY_TYPE ) VALUES( 11,'DEBIT',	11);

INSERT INTO BANK_TRANSACTION_CODE( CODE,NAME,ENTRY_TYPE ) VALUES(1000,'TOPUP',	 0);
INSERT INTO BANK_TRANSACTION_CODE( CODE,NAME,ENTRY_TYPE ) VALUES(1010,'TOPCR',	10);
INSERT INTO BANK_TRANSACTION_CODE( CODE,NAME,ENTRY_TYPE ) VALUES(1011,'TOPDB',	10);

INSERT INTO BANK_TRANSACTION_CODE( CODE,NAME,ENTRY_TYPE ) VALUES(2100,'PAY',	 0);
INSERT INTO BANK_TRANSACTION_CODE( CODE,NAME,ENTRY_TYPE ) VALUES(2110,'PAY-CR',	10);
INSERT INTO BANK_TRANSACTION_CODE( CODE,NAME,ENTRY_TYPE ) VALUES(2111,'PAY-DR',	11);


INSERT INTO BANK_TRANSACTION_CODE( CODE,NAME,ENTRY_TYPE ) VALUES(3100,'LOANTX',	 0);
INSERT INTO BANK_TRANSACTION_CODE( CODE,NAME,ENTRY_TYPE ) VALUES(3110,'LOAN-CR',10);
INSERT INTO BANK_TRANSACTION_CODE( CODE,NAME,ENTRY_TYPE ) VALUES(3111,'LOAN-DR',11);

