DROP TABLE BANK_TRANSACTION_CODE IF EXISTS;

CREATE TABLE BANK_TRANSACTION_CODE (

			CODE 					INT,
			NAME 					VARCHAR(20),
			ENTRY_TYPE 				INT,
			DATE_CREATED 			TIMESTAMP DEFAULT CURRENT_TIMESTAMP
			
);

DROP TABLE BANK_ACCOUNT_TRANSACTIONS IF EXISTS;

CREATE TABLE BANK_ACCOUNT_TRANSACTIONS (
			
			TRANSACTION_ID			INT NOT NULL AUTO_INCREMENT,
			ACCOUNT_USERNAME 		VARCHAR(20),
			TRANCODE 				INT,
			ACCOUNT_ENTRY_TYPE		INT,
			AMOUNT 					DECIMAL(500000,4),
			TRANSACTION_DATE 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE BANK_LOAN_LEDGER (
			
			LOAN_ID					INT NOT NULL AUTO_INCREMENT,
			CREDITOR_USERNAME 		VARCHAR(20),
			DEBITOR_USERNAME 		VARCHAR(20),
			AMOUNT 					DECIMAL(500000,4),
			TRANSACTION_DATE 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


DROP TABLE BANK_CLIENT IF EXISTS;

CREATE TABLE BANK_CLIENT (

			USERNAME 				VARCHAR(20)

);

DROP TABLE USER_SESSION IF EXISTS;

CREATE TABLE USER_SESSION (

			SESSION_ID 				INT NOT NULL AUTO_INCREMENT,
			USERNAME 				VARCHAR(20),
			LOGIN_DATE 				TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


